language: r

CRAN: https://cloud.r-project.org

before_script:
    - chmod +x ./_build.sh
    - chmod +x ./_deploy.sh

script:
    - set -e
    - ./_build.sh
    - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ]; then ./_deploy.sh; fi
