sudo: false
notifications:
    email: false

language: r

cache:
  packages: yes

before_script:
    - chmod +x ./_build.sh
    - chmod +x ./_deploy.sh

script:
    - set -e
    - ./_build.sh
    - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ]; then ./_deploy.sh; fi
